### ISSUE TITLE
Workflow fails when installing VIS (dependency)

### ISSUE THREAD

**Issue by gaudes** [ioBroker/testing#467] opened 2022-02-01 20:05 UTC
Hey,

I'm not sure where to open this issue.

In my project I currently have the problem, that my test-and-release workflow fails after 30 minutes when trying to install VIS, which is a dependency.

This is my project:
https://github.com/gaudes/ioBroker.slideshow

Attached is the log from the workflow.
[2_Run ioBrokertesting-action-adapter@v1.txt](https://github.com/ioBroker/testing/files/7981621/2_Run.ioBrokertesting-action-adapter%40v1.txt)

Kind regards,

Ralf

**Comment by AlCalzone** [comment] 2022-02-01 22:21
Duplicate of #466

**Comment by AlCalzone** [comment] 2022-02-01 22:21
But thanks :)

**Closed by AlCalzone** 2022-02-01 22:21 UTC

**Comment by AlCalzone** [comment] 2022-02-02 15:28
Fixed in 2.5.4
