### ISSUE TITLE
Typescript & Unit Testing

### ISSUE THREAD

**Issue by xDGeForcexD** [ioBroker/testing#317] opened 2020-08-04 15:02 UTC
Hi,
I want to write my first adapter for ioBroker. I want also to write unit tests for my adapter to check if states will be creating right and check if it handle right but I get it not working.

My idea is that I need this Module to mock the adapter and js-controller. Is this right?

I created my adapter with the "npx @iobroker/create-adapter" and I select the Typescript variant.

If I change the src/main.test.ts with the example from this repo and I run it there a lot of errors like: 
`build/main.js:27:17 - error TS2683: 'this' implicitly has type 'any' because it does not have a type annotation.`

I think the problem is that the builded files (javascript) will be executed and not the src files from the adapter.
If I turned on the Debug Mode I get this entry file: 
 `testing:unit:adapterTools   => found build/main.js +1ms`
Should the entry file for Typescript not this `src/main.ts`?

Is this a Bug or what is my mistake?

I hope someone can me help :)

Best regards
xDGeForcexD

PS: I changed the example code a little bit:
```typescript

import { tests, utils } from "@iobroker/testing";
import path = require("path");

tests.unit(path.join(__dirname, ".."), {
	//     ~~~~~~~~~~~~~~~~~~~~~~~~~
	// This should be the adapter's root directory

	// Define your own tests inside defineAdditionalTests
	defineAdditionalTests() {
		// Create mocks and asserts
		const { adapter, database } = utils.unit.createMocks({});

		describe("my test", () => {
			afterEach(() => {
				// The mocks keep track of all method invocations - reset them after each single test
				adapter.resetMockHistory();
				// We want to start each test with a fresh database
				database.clear();
			});

			it("works", () => {
				// Do something that should be tested
				console.log(database.getObjects("*"));
			});
		});
	},
});
```

**Comment by AlCalzone** [comment] 2020-08-04 16:00
I'll check it out but I'm on vacation the next two weeks.

**Comment by AlCalzone** [comment] 2020-08-16 14:24
Do you have a link to a repo of your adapter where I can check this out myself?

**Comment by xDGeForcexD** [comment] 2020-08-17 09:17
I deleted the test.

I have now created the test under this repo and branch: 
https://github.com/xDGeForcexD/ioBroker.ah-mixer/tree/testing-issue

The "main.test.ts" will be not executed so I don't can reproduce the problem. Maybe you find why the test is not loaded.

**Comment by AlCalzone** [comment] 2020-08-18 17:44
Okay, so the problem is that mocha 8 requires a rc file instead of an opts file and this causes your tests to fail. What you need to do:
1. delete `test/mocha.custom.opts`
2. add a `.mocharc.json` file in the project root:
    ```json
    {
    	"require": ["./test/mocha.setup.js", "ts-node/register", "source-map-support/register"],
    	"watch-files": ["src/**/*.test.ts"]
    }
    ```
3. change the `test:ts` script to `mocha src/**/*.test.ts`

![grafik](https://user-images.githubusercontent.com/17641229/90547080-41de1a80-e18b-11ea-8301-4ce0e93ff9cb.png)

**Comment by AlCalzone** [comment] 2020-08-20 17:58
Closing this, since it is not a bug in this library. Feel free to reopen if it doesn't work for you.

**Closed by AlCalzone** 2020-08-20 17:58 UTC
